#!/usr/bin/env bash
#MISE description="Lint Workspace"

set -e
golangci-lint run ./...
mapfile -t submodules < <(find . -mindepth 2 -name go.mod | xargs -n1 dirname | sed 's|^\./||' | sort)
for d in "${submodules[@]}"; do
  (cd "$d" && golangci-lint run ./...)
done
