#!/usr/bin/env bash
#MISE description="Test Workspace"

set -e
go test ./... -race
mapfile -t submodules < <(find . -mindepth 2 -name go.mod | xargs -n1 dirname | sed 's|^\./||' | sort)
for d in "${submodules[@]}"; do
  (cd "$d" && go test ./... -race)
done
