#!/usr/bin/env bash
#MISE description="Vet Workspace"

set -e
go vet ./...
mapfile -t submodules < <(find . -mindepth 2 -name go.mod | xargs -n1 dirname | sed 's|^\./||' | sort)
for d in "${submodules[@]}"; do
  (cd "$d" && go vet ./...)
done
