package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

const generateTestModelsSrc = `package models

import "github.com/asimmons91/trails/pack"

type Widget struct {
	pack.Model[int64] ` + "`db:\"table:widgets\"`" + `
	Name string ` + "`db:\"name,not_null\"`" + `
}
`

// repoRoot resolves the trails repo root from outside a chdirTemp'd
// directory, for use in a go.mod replace directive.
func repoRoot(t *testing.T) string {
	t.Helper()

	out, err := exec.Command("go", "env", "GOMOD").Output()
	require.NoError(t, err)

	return filepath.Dir(strings.TrimSpace(string(out)))
}

func TestFieldsCmd_GeneratesCompilableOutput(t *testing.T) {
	root := repoRoot(t)
	chdirTemp(t)

	writeFile(t, "go.mod", fmt.Sprintf(
		"module tmpapp\n\ngo 1.27\n\nrequire github.com/asimmons91/trails v0.0.0\n\nreplace github.com/asimmons91/trails => %s\n",
		root,
	))
	writeFile(t, "app/models/widget.go", generateTestModelsSrc)

	cmd := FieldsCmd{Dir: "app/models", Out: "trails_fields_gen.go"}
	require.NoError(t, cmd.Run())

	genPath := filepath.Join("app", "models", "trails_fields_gen.go")
	got, err := os.ReadFile(genPath)
	require.NoError(t, err)
	require.Contains(t, string(got), "// Code generated by trails generate fields. DO NOT EDIT.")
	require.Contains(t, string(got), "var WidgetFields = struct")

	// Rerun must not deadlock on the file it just wrote (see load.go's
	// overlay handling for stale generated output).
	require.NoError(t, cmd.Run())

	out, err := exec.Command("go", "mod", "tidy").CombinedOutput()
	require.NoErrorf(t, err, "go mod tidy failed:\n%s", out)

	out, err = exec.Command("go", "build", "./...").CombinedOutput()
	require.NoErrorf(t, err, "generated code does not compile:\n%s", out)
}
