package fieldsgen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"sort"
	"text/template"
)

const packImportPath = "github.com/asimmons91/trails/pack"

const fileTemplate = `// Code generated by trails generate fields. DO NOT EDIT.

package {{.Package}}
{{if .Imports}}
import (
{{- range .Imports}}
	{{if .Alias}}{{.Alias}} {{end}}"{{.Path}}"
{{- end}}
)
{{end}}
{{range .Models}}{{$m := .}}
{{- range .Skipped}}
// {{.GoName}} intentionally omitted from {{$m.Name}}Fields: {{.Reason}}
{{end -}}
{{- if or .Cols .Rels}}
var {{.Name}}Fields = struct {
{{- range .Cols}}
	{{.GoName}} pack.Col[{{$m.Name}}, {{.TypeExpr}}]
{{- end}}
{{- range .Rels}}
	{{.GoName}} pack.Rel[{{$m.Name}}, {{.TargetTypeExpr}}]
{{- end}}
}{
{{- range .Cols}}
	{{.GoName}}: pack.Field(func(m *{{$m.Name}}) *{{.TypeExpr}} { return &m.{{.GoName}} }),
{{- end}}
{{- range .Rels}}
{{- if .Many}}
	{{.GoName}}: pack.Relation(func(m *{{$m.Name}}) *[]*{{.TargetTypeExpr}} { return &m.{{.GoName}} }),
{{- else}}
	{{.GoName}}: pack.RelationOne(func(m *{{$m.Name}}) **{{.TargetTypeExpr}} { return &m.{{.GoName}} }),
{{- end}}
{{- end}}
}
{{end}}
{{end}}
`

var fileTmpl = template.Must(template.New("fields_gen").Parse(fileTemplate))

type tplImport struct {
	Alias string
	Path  string
}

type tplCol struct {
	GoName   string
	TypeExpr string
}

type tplRel struct {
	GoName         string
	TargetTypeExpr string
	Many           bool
}

type tplModel struct {
	Name    string
	Cols    []tplCol
	Rels    []tplRel
	Skipped []SkippedField
}

type tplFile struct {
	Package string
	Imports []tplImport
	Models  []tplModel
}

type importEntry struct {
	Path    string
	Default string // the package's own declared name
	Local   string // the name actually used in generated code
}

// render turns the flattened models into a formatted Go source file in
// package pkgName, using selfPkg to know which referenced types belong to
// the file's own package (and so need no qualifier).
func render(pkgName string, selfPkg *types.Package, models []ModelInfo) ([]byte, error) {
	imports := map[string]*importEntry{}
	used := map[string]bool{"pack": true}
	needsPack := false

	qualifier := func(p *types.Package) string {
		if p == selfPkg {
			return ""
		}
		if e, ok := imports[p.Path()]; ok {
			return e.Local
		}

		local := p.Name()
		for n := 1; used[local]; n++ {
			local = fmt.Sprintf("%s%d", p.Name(), n)
		}
		used[local] = true
		imports[p.Path()] = &importEntry{Path: p.Path(), Default: p.Name(), Local: local}

		return local
	}

	data := tplFile{Package: pkgName}
	for _, m := range models {
		tm := tplModel{Name: m.Name, Skipped: m.Skipped}

		for _, c := range m.Cols {
			needsPack = true
			tm.Cols = append(tm.Cols, tplCol{
				GoName:   c.GoName,
				TypeExpr: types.TypeString(c.Type, qualifier),
			})
		}

		for _, r := range m.Rels {
			needsPack = true
			tm.Rels = append(tm.Rels, tplRel{
				GoName:         r.GoName,
				TargetTypeExpr: types.TypeString(r.Target, qualifier),
				Many:           r.Kind == RelMany,
			})
		}

		data.Models = append(data.Models, tm)
	}

	if needsPack {
		if _, ok := imports[packImportPath]; !ok {
			imports[packImportPath] = &importEntry{Path: packImportPath, Default: "pack", Local: "pack"}
		}
	}

	data.Imports = sortedImports(imports)

	var buf bytes.Buffer
	if err := fileTmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w\n%s", err, buf.String())
	}

	return formatted, nil
}

func sortedImports(imports map[string]*importEntry) []tplImport {
	paths := make([]string, 0, len(imports))
	for p := range imports {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	out := make([]tplImport, 0, len(paths))
	for _, p := range paths {
		e := imports[p]
		alias := ""
		if e.Local != e.Default {
			alias = e.Local
		}
		out = append(out, tplImport{Alias: alias, Path: e.Path})
	}

	return out
}
